### ISSUE TITLE
Broken link to package website

### ISSUE THREAD

**Issue by mylesstokowski** [ebird/ebirdst#6]
Hello maintainers! 

This isn't _directly_ related to the package itself, so let me know if there's a better place to post this. Or perhaps this is already a known issue. 

Just wanted to give a heads up that the `Install R package` button on the download data [page](https://science.ebird.org/en/status-and-trends/download-data) appears to be broken. Currently, it points to https://cornelllabofornithology.github.io/ebirdst/index.html, where I'm seeing this: 
![Screenshot 2023-12-15 at 9 06 11 AM](https://github.com/ebird/ebirdst/assets/35432444/8dfbe040-86b8-4513-a236-b26bd20d5d44)

I suspect you may want it to point to https://ebird.github.io/ebirdst/. FWIW, I also get the broken link as the first search result on Google:
![image](https://github.com/ebird/ebirdst/assets/35432444/97e0df14-58be-49dd-961e-2b5b2dfd1fea)

**Comment by mstrimas** [comment]
thanks for catching this, I'll try to get someone to fix that link asap! I suspect you've already found it, but the correct link is https://ebird.github.io/ebirdst/

**Comment by mstrimas** [comment]
The link on the S&T website is now updated.
